ci/cd:
  - changed-files:
      - any-glob-to-any-file: ".github/workflows/**"

tests:
  - changed-files:
      - any-glob-to-any-file: "playwright/**"
      - any-glob-to-any-file: "src/**"

documentation:
  - changed-files:
      - any-glob-to-any-file: "**/*.md"

dependencies:
  - changed-files:
      - any-glob-to-any-file: "package.json"
      - any-glob-to-any-file: "package-lock.json"
