export default {
  'APP_SHIPMENT_UPDATE': 'APP_SHIPMENT_UPDATE',
  'APP_SHIPMENT_ADMIN': 'APP_SHIPMENT_ADMIN',
  'APP_PRODUCT_IDENTIFIER_UPDATE': 'APP_PRODUCT_IDENTIFIER_UPDATE',
  'APP_COMMERCE_VIEW': 'APP_COMMERCE_VIEW'
}