import { beforeEach, expect, it, vi } from 'vitest';
import { createPinia, setActivePinia } from 'pinia';
const api = vi.hoisted(() => vi.fn());
vi.mock('@common/core/remoteApi', () => ({ default: api }));
vi.mock('@common/core/logger', () => ({ default: {error: vi.fn()} }));
vi.mock('@common/core/i18n', () => ({ translate: (text: string) => text }));
vi.mock('@common/store/embeddedApp', () => ({ useEmbeddedAppStore: vi.fn() }));
vi.mock('@common/composables/useSolrSearch', () => ({ useSolrSearch: vi.fn() }));
vi.mock('@/store/user', () => ({ useUserStore: vi.fn() }));
import { useProductStore } from './productStore';
beforeEach(() => { setActivePinia(createPinia()); vi.clearAllMocks(); });
it('waits for the selected product store settings before returning its product stores', async () => {
  const store = useProductStore(); store.currentFacility = {facilityId: 'BROADWAY', productStores: []};
  api.mockResolvedValueOnce({data:[{productStoreId:'STORE'}]}).mockResolvedValueOnce({data:[{productStoreId:'STORE',storeName:'Demo'}]});
  let resolve!: () => void;
  const settings = new Promise<void>(done => {resolve=done;});
  const dependencies = vi.spyOn(store, 'fetchProductStoreDependencies').mockReturnValue(settings);
  let settled = false;
  const fetch = store.fetchProductStores().then(() => {settled=true;});
  await vi.waitFor(() => expect(dependencies).toHaveBeenCalledWith('STORE'));
  expect(settled).toBe(false);
  resolve(); await fetch;
  expect(dependencies).toHaveBeenCalledOnce();
  expect(store.getCurrentProductStore.productStoreId).toBe('STORE');
});
