export const SN_PURCHASE_ORDER = 'purchase_order'
export const PURCHASE_ORDER_UPDATED = SN_PURCHASE_ORDER + '/UPDATED'
export const PURCHASE_ORDER_DETAIL_UPDATED = SN_PURCHASE_ORDER+ '/DETAIL_UPDATED'
export const PURCHASE_ORDER_PRODUCT_COUNT_UPDATED = SN_PURCHASE_ORDER + '/PRODUCT_COUNT_UPDATED'