export const SN_SHIPMENT = 'shipment'
export const SHIPMENT_LIST_UPDATED = SN_SHIPMENT + '/SEARCH_UPDATED'
export const SHIPMENT_REMOVE_FROM_SHPMT_PRDTS = SN_SHIPMENT + '/REMOVE_FROM_SHPMT_PRDTS'
export const SHIPMENT_CURRENT_UPDATED = SN_SHIPMENT + '/CURRENT'