export const SN_PRODUCT = 'product'
export const PRODUCT_SEARCH_UPDATED = SN_PRODUCT + '/SEARCH_UPDATED'
export const PRODUCT_CURRENT = SN_PRODUCT + '/CURRENT'
export const PRODUCT_ADD_TO_SHPMT_PRDTS = SN_PRODUCT + '/ADD_TO_SHPMT_PRDTS'
export const PRODUCT_REMOVE_FROM_SHPMT_PRDTS = SN_PRODUCT + '/REMOVE_FROM_SHPMT_PRDTS'

