export const SN_SHIPMENT = 'shipment'
export const SHIPMENT_SEARCH_UPDATED = SN_SHIPMENT + '/SEARCH_UPDATED'
export const SHIPMENT_CURRENT = SN_SHIPMENT + '/CURRENT'
export const SHIPMENT_REMOVE_FROM_SHPMT_PRDTS = SN_SHIPMENT + '/REMOVE_FROM_SHPMT_PRDTS'

